config/routes.rb
Rails.application.routes.draw do

  # デバイス
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ルートページ
  root 'home#top'

  # ユーザー機能
  resources :users, only:[:show, :edit, :update] do
    member do
      get "like_rooms"
      get "review_rooms"
    end
  end

  # 投稿機能
  resources :rooms do
    resources :reviews, shallow: true # レビュー機能
    member do
      get "liking_users"
      get "review_users"
    end
    collection do
      get "search"
    end
  end

  # いいね機能
  post "/like/:room_id" => "likes#like", as: "like"
  delete "/unlike/:room_id" => "likes#unlike", as: "unlike"

  # お問い合わせ機能
  get "/contact" => "contacts#new"
  post "/contact" => "contacts#create"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  # アップローダー
  mount_uploader :image, ImageUploader

  # バリデーション
  validates :name, presence: true

  # アソシエーション
  has_many :rooms
  has_many :likes, dependent: :destroy
  has_many :like_rooms, through: :likes, source: :room
  has_many :reviews, dependent: :destroy
  has_many :review_rooms, through: :reviews, source: :room

  # twitterログイン
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.image = auth.info.image
    end
  end

  # twitterからデータを取得
  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"]) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  # twitterでパスワードを要求しないようにする
  def password_required?
    super && provider.blank?
  end

  # passwordなしでも更新できるようにする
  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  # twitterログイン
  def twitter
    callback_from :twitter
  end

  private

  def callback_from(provider)
    @user = User.from_omniauth(request.env["omniauth.auth"].except("extra"))
    if @user.persisted?
      flash[:notice] = "Twitter authentication succeeded."
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.user_attributes"] = @user.attributes
      redirect_to new_user_registration_url
    end
  end

  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # ログイン必須
  before_action :authenticate_user!
  # ビフォーアクション
  before_action :set_user, only: [:show, :edit, :update, :like_rooms, :review_rooms, :correct_user]
  # ログイン中のユーザーのビフォーアクション
  before_action :correct_user, only:[:edit, :update]

  # ユーザー詳細
  def show
    @rooms = @user.rooms.order(created_at: :desc)
    @review_rooms = @user.review_rooms.order(created_at: :desc)
    @like_rooms = @user.like_rooms.order(created_at: :desc)
  end

  # ユーザー編集
  def edit
    #code
  end

  # ユーザー編集
  def update
    if @user.update(user_params)
      flash[:success] = "User information updated."
      redirect_to @user
    else
      render :edit
    end
  end


  # ユーザーのいいね一覧
  def like_rooms
    @rooms = @user.like_rooms
  end

  # ユーザーのレビュー一覧
  def review_rooms
    @rooms = @user.review_rooms
  end

  private

  # ビフォーアクション
  def set_user
    @user = User.find(params[:id])
  end

  # ストロングパラメーター
  def user_params
    params.require(:user).permit(:name, :email, :image, :image_cache)
  end

  # ログインしているユーザーが正しいか
  def correct_user
    unless current_user?(@user)
      redirect_to root_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user, html: { multipart: true }) do |f| %>
        <%= render 'shared/errors', object: f.object %>
        <div class="form-group">
          <%= image_tag @user.image.url if @user.image? %>
          <%= f.hidden_field :image_cache %>
          <%= f.label :image %>
          <%= f.file_field :image, class: "form-control-file" %>
        </div>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="action">
          <%= f.submit "Save", class: "btn btn-primary btn-block" %>
        </div>
      <% end %>
    </div>
    <p>Unhappy? <%= button_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %></p>
    <%= link_to "Delete", user_path(@user), method: :delete, data: { confirm: 'Are you sure?' } %>
    <%= link_to "User edit", edit_user_registration_path %>
  </div>
</div>

app/views/users/_user.html.erb
<li>
  <%= image_tag user.image.url if user.image? %>
  <%= user.name %>
</li>

app/views/users/edit.html.erb
<% @page_title = "Edit" %>

<%= render "form" %>

app/views/users/review_rooms.html.erb
<ul>
  <li><%= render @rooms %></li>
</ul>

app/views/users/show.html.erb
<% @page_title = current_user.name %>

<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <aside class="user-info">
        <section>
          <% if @user.image? %>
            <%= image_tag @user.image.url %>
          <% else %>
            <%= image_tag "default-image.png" %>
          <% end %>
        </section>
        <section>
          <%= @user.name %>
        </section>
        <section>
          <% if current_user?(@user) %>
          <%= link_to "Edit", edit_user_path(@user) %>
          <% end %>
        </section>
      </aside>
    </div>

    <div class="col-sm-8">
    <ul class="nav nav-tabs">
      <li class="active">
        <a href="#rooms" data-toggle="tab">Rooms (<%= @user.rooms.count %>)</a>
      </li>
      </li>
      <li>
        <a href="#reviews" data-toggle="tab">Reviews (<%= @user.reviews.count %>)</a>
      </li>
      <li>
        <a href="#likes" data-toggle="tab">Likes (<%= @user.likes.count %>)</a>
      </li>
    </ul>

    <div class="tab-content">
      <div id="rooms" class="tab-pane active">
        <ul class="room-index">
          <%= render @rooms %>
        </ul>
      </div>
      <div id="reviews" class="tab-pane">
        <ul class="room-index">
          <%= render @review_rooms %>
        </ul>
      </div>
      <div id="likes" class="tab-pane">
        <ul class="room-index">
          <%= render @like_rooms %>
        </ul>
      </div>
    </div>

    </div>

  </div>

</div>