config/routes.rb
Rails.application.routes.draw do

  # デバイス
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ルートページ
  root 'home#top'

  # ユーザー機能
  resources :users, only:[:show, :edit, :update] do
    member do
      get "like_rooms"
      get "review_rooms"
    end
  end

  # 投稿機能
  resources :rooms do
    resources :reviews, shallow: true # レビュー機能
    member do
      get "liking_users"
      get "review_users"
    end
    collection do
      get "search"
    end
  end

  # いいね機能
  post "/like/:room_id" => "likes#like", as: "like"
  delete "/unlike/:room_id" => "likes#unlike", as: "unlike"

  # お問い合わせ機能
  get "/contact" => "contacts#new"
  post "/contact" => "contacts#create"

end

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h3><%= object.errors.count %>件のエラーがあります。</h3>
    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="container">
    ここにフッター
  </div>
</footer>

app/views/shared/_header.html.erb
<!-- ここからヘッダー -->
<header id="fixed-navigation" canvas="">
  <!-- ヘッダーインナー -->
  <div class="container-fluid header-inner">
    <!-- ロゴ -->
    <div class="header-left">
      <%= link_to "logo", root_path %>
    </div>
    <!-- スマホ用のメニュー -->
    <div class="visible-xs">
      <div class="header-right">
        <nav class="menu">
        <ul>
          <% if user_signed_in? %>
          <li class="menu-icon">
            <%= link_to rooms_path do %>
              <span class="fa fa-search"></span>
            <% end %>
          </li>
          <li class="menu-icon">
            <%= link_to new_room_path do%>
              <span class="fa fa-pencil-square-o"></span>
            <% end %>
          </li>
          <div class="menu-icon">
            <div class="fa fa-bars sb-open-right"></div>
          </div>
          <% else %>
          <li><%= link_to "ログイン", "#" %></li>
          <% end %>
        </ul>
        </nav>
      </div><!-- header-right -->
    </div><!-- visible-xs -->
    <!-- パソコン・タブレット用のメニュー -->
    <div class="hidden-xs">
      <div class="header-right">
        <nav class="menu">
        <ul>
          <% if user_signed_in? %>
          <li><%= link_to "Search", rooms_path %></li>
          <li><%= link_to "Post", new_room_path %></li>
          <li><%= link_to current_user.name, current_user %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <% end %>
        </ul>
        </nav>
      </div>
    </div>
  </div>
</header>