config/routes.rb
Rails.application.routes.draw do

  # デバイス
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ルートページ
  root 'home#top'

  # ユーザー機能
  resources :users, only:[:show, :edit, :update] do
    member do
      get "like_rooms"
      get "review_rooms"
    end
  end

  # 投稿機能
  resources :rooms do
    resources :reviews, shallow: true # レビュー機能
    member do
      get "liking_users"
      get "review_users"
    end
    collection do
      get "search"
    end
  end

  # いいね機能
  post "/like/:room_id" => "likes#like", as: "like"
  delete "/unlike/:room_id" => "likes#unlike", as: "unlike"

  # お問い合わせ機能
  get "/contact" => "contacts#new"
  post "/contact" => "contacts#create"

end

app/models/room.rb
require 'file_size_validator'
class Room < ApplicationRecord

  # アップローダー
  mount_uploader :picture, PictureUploader

  # バリデーション
  validates :picture, file_size: {maximum: 5.megabytes.to_i}
  validates :name, presence: true

  # google map
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

  # アソシエーション
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
  has_many :reviews, dependent: :destroy
  has_many :review_users, through: :reviews, source: :user

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # ビフォーアクション
  before_action :set_room, only: [:show, :edit, :update, :destroy, :liking_users, :review_users]

  # 一覧
  def index
    @rooms = Room.all.order(created_at: :desc).page(params[:page])
  end

  # 詳細
  def show
    @reviews = @room.reviews
  end

  # 新規作成
  def new
    @room = Room.new
  end

  # 新規作成
  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      flash[:success] = "Post was successfully created."
      redirect_to @room
    else
      render :new
    end
  end

  # アップデート
  def edit
    #code
  end

  # アップデート
  def update
    if @room.update(room_params)
      flash[:success] = "Post was successfully updated."
      redirect_to @room
    else
      render :edit
    end
  end

  # 削除
  def destroy
    @room.destroy
    flash[:success] = "Post was successfully destroyed."
    redirect_to root_path
  end

  # いいねしてるユーザー
  def liking_users
    @users = @room.liking_users
  end

  # レビューしてるユーザー
  def review_users
    @users = @room.review_users
  end

  private

  # ビフォーアクション
  def set_room
    @room = Room.find(params[:id])
  end

  # ストロングパラメーター
  def room_params
    params.require(:room).permit(:name, :picture, :picture_cache, :access, :address, :rent, :floor_plan, :direction, :structure, :storey, :built, :exclusive_area, :notes, :latitude, :longitude, :user_id)
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@room, html: {multipart: true}) do |f| %>
        <%= render "shared/errors", object: f.object %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :address %>
        <%= f.text_field :address, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :access %>
        <%= f.text_field :access, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :rent %>
        <%= f.text_field :rent, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :floor_plan %>
        <%= f.text_field :floor_plan, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :direction %>
        <%= f.text_field :direction, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :structure %>
        <%= f.text_field :structure, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :storey %>
        <%= f.text_field :storey, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :built %>
        <%= f.text_field :built, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :exclusive_area %>
        <%= f.text_field :exclusive_area, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :notes %>
        <%= f.text_area :notes, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= image_tag @room.picture.url(:thumb) if @room.picture? %>
        <%= f.hidden_field :picture_cache %>
        <%= f.label :picture %>
        <%= f.file_field :picture, class: "form-control-file" %>
      </div>
      <div class="actions">
        <%= f.submit "投稿する", class: "btn btn-primary btn-block" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/_room.html.erb
<li>
  <%= link_to room do %>
  <div class="list-inner">
    <div class="list-image">
      <% if room.picture? %>
      <%= image_tag room.picture.url(:thumb) %>
      <% else %>
      <%= image_tag "default-room-image" %>
      <% end %>
    </div>
    <div class="list-block">
      <p><%= room.name %></p>
      <p><%= room.address %></p>
      <p><%= room.access %></p>
    </div>
  </div>
  <% end %>
</li>

app/views/rooms/edit.html.erb
<% @page_title = "Edit" %>

<%= render "form" %>

app/views/rooms/index.html.erb
<% @page_title = "Index" %>

<div class="container">
  <div class="row">
    <%= page_entries_info @rooms %>
    <ul class="room-index">
      <%= render @rooms %>
    </ul>
    <%= paginate @rooms %>
  </div>
</div>

app/views/rooms/new.html.erb
<% @page_title = "New Post" %>

<%= render "form" %>

app/views/rooms/review_users.html.erb
<% @page_title = "Users" %>

<ul>
  <%= render @users %>
</ul>

app/views/rooms/show.html.erb
<% @page_title = @room.name %>

<div class="container">
  <div class="row">
    <!-- ここからコンテンツ左側 -->
    <div class="col-sm-8">
      <article class="article">
        <!-- ここから部屋の名前 -->
        <div class="heading room-name-heading">
          <h1><%= @room.name %></h1>
        </div><!-- ここまで部屋の名前 -->

        <!-- ここから部屋のイメージ -->
        <div class="room-picture">
          <% if @room.picture? %>
          <%= image_tag @room.picture.url %>
          <% else %>
          <%= image_tag "default-room-image.jpg" %>
          <% end %>
        </div><!-- ここまで部屋の画像 -->

        <!-- ここから部屋の基本情報 -->
        <div class="heading">
          <h1>Basic information</h1><%= link_to 'Edit', edit_room_path(@room) %>
        </div>
        <!-- ここからテーブル -->
        <div class="table-responsive">
          <table class="table table-bordered table-condensed">
            <tbody>
              <tr>
                <th scope="row">Name</th>
                <td><%= @room.name %></td>
              </tr>
              <tr>
                <th>Access</th>
                <td><%= @room.access %></td>
              </tr>
              <tr>
                <th>Address</th>
                <td><%= @room.address %></td>
              </tr>
              <tr>
                <th>Rent</th>
                <td><%= @room.rent %></td>
              </tr>
              <tr>
                <th>Floor plan</th>
                <td><%= @room.floor_plan %></td>
              </tr>
            </tbody>
          </table>
        </div><!-- ここまでテーブル -->

        <!-- ここから部屋の詳細情報 -->
        <div class="heading">
          <h1>More information</h1>
        </div>
        <!-- ここからテーブル -->
        <div class="table-responsive">
          <table class="table table-bordered table-condensed">
            <tbody>
              <tr>
                <th>Direction</th>
                <td><%= @room.direction %></td>
              </tr>
              <tr>
                <th>Structure</th>
                <td><%= @room.structure %></td>
              </tr>
              <tr>
                <th>Storey</th>
                <td><%= @room.storey %></td>
              </tr>
              <tr>
                <th>Built</th>
                <td><%= @room.built %></td>
              </tr>
              <tr>
                <th>Exclusive area</th>
                <td><%= @room.exclusive_area %></td>
              </tr>
            </tbody>
          </table>
        </div><!-- ここまでテーブル -->

        <!-- ここからその他の情報と編集・削除ボタン -->
        <div class="heading">
          <h1>Notes</h1>
        </div>
        <div class="room-note">
          <%= @room.notes %>
        </div>
        <div class="edit">
          <%= link_to 'Edit', edit_room_path(@room), class: "btn btn-warning" %>
          <%= link_to 'Destroy', room_path(@room), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </div><!-- ここまでその他 -->

        <!-- ここから部屋の地図 -->
        <div class="heading">
          <h1>Map</h1>
        </div>
        <div class="room-map">
          <%= image_tag "http://maps.google.com/maps/api/staticmap?size=750x300&sensor=false&zoom=16&markers=#{@room.latitude}%2C#{@room.longitude}" %>
        </div>

        <!-- ここからレビュー -->
        <div class="heading">
          <h1>Reviews</h1>
        </div>
        <%= @room.reviews.count %>

        <!-- コメントしてるかどうか -->
        <% if user_signed_in? %>
        <% if current_user.reviews.find_by(room_id: @room.id) %>
        <P>※あなたはこの投稿にコメント済みです。</P>
        <% end %>
        <% end %><!-- ここまでコメントしてるかどうか -->

        <%= link_to "Add review", new_room_review_path(@room), class: "btn btn-primary" %>
        <ul>
          <% if @room.reviews.any? %>
          <%= render @room.reviews %>
          <% else %>
          <strong>no reviews yet</strong>
          <% end %>
        </ul>

      </article><!-- articleここまで -->
    </div><!-- ここまでコンテンツ左側 -->


    <!-- ここからコンテンツ右側 -->
    <div class="col-sm-4">
      <aside class="sidebar">
        <section>
          <!-- ここからいいね！ -->
          <div class="like-wrapper">
            <div id="like-link" class="btn btn-danger">
              <%= render "likes/like_links", room: @room %>
            </div>
            <div id="like-count">
              <%= @room.likes.count %>
            </div>
          </div><!-- ここまでいいね！ -->
        </section>

        <section>
          <!-- ここから近い部屋一覧 -->
          <ul>
            <% for room in @room.nearbys(10) %>
            <li><%= link_to room.name, room %></li>
            <% end %>
          </ul><!-- ここまで部屋一覧 -->
        </section>
      </aside>
    </div><!-- ここまでコンテンツ右側 -->

  </div><!-- rowここまで -->
</div> <!-- containerここまで -->