config/routes.rb
Rails.application.routes.draw do

  # デバイス
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ルートページ
  root 'home#top'

  # ユーザー機能
  resources :users, only:[:show, :edit, :update] do
    member do
      get "like_rooms"
      get "review_rooms"
    end
  end

  # 投稿機能
  resources :rooms do
    resources :reviews, shallow: true # レビュー機能
    member do
      get "liking_users"
      get "review_users"
    end
    collection do
      get "search"
    end
  end

  # いいね機能
  post "/like/:room_id" => "likes#like", as: "like"
  delete "/unlike/:room_id" => "likes#unlike", as: "unlike"

  # お問い合わせ機能
  get "/contact" => "contacts#new"
  post "/contact" => "contacts#create"

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  # ビフォーアクション
  before_action :find_room, only:[:index, :new, :create]
  # ログイン必須
  before_action :authenticate_user!

  # レビュー一覧
  def index
    @reviews = @room.reviews
  end

  # レビュー詳細
  def show
    #code
  end

  # レビュー投稿
  def new
    @review = @room.reviews.build
  end

  # レビュー編集
  def edit
    @review = Review.find(params[:id])
  end

  # レビュー投稿
  def create
    @review = current_user.reviews.build(review_params)
    @review.room_id = @room.id
    if @review.save
      flash[:success] = "レビューを投稿しました。"
      redirect_to room_url(@review.room_id)
    else
      render :new
    end
  end

  # レビュー編集
  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      flash[:success] = "レビューを更新しました。"
      redirect_to room_url(@review.room_id)
    else
      render :edit
    end
  end

  # レビュー削除
  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:success] = "レビューを削除しました。"
    redirect_to room_url(@review.room_id)
  end

  private

  # ビフォーアクション
  def find_room
    @room = Room.find(params[:room_id])
  end

  # ストロングパラメーター
  def review_params
    params.require(:review).permit(:content)
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for([@room, @review]) do |f| %>
  <%= render 'shared/errors', object: f.object %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control" %>
  </div>
  <div class="action">
    <%= f.submit "登録する", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/reviews/_review.html.erb
<li>
  <div class="review-user">
    <%= review.user.image %>
    <%= review.user.name %>
  </div>
  <div class="review-content">
    <%= review.content %>
  </div>

  <%= link_to "edit",  edit_review_path(review) %>
  <%= link_to "delete", review_path(review), method: :delete, data: { confirm: 'Are you sure?' } %>
</li>

app/views/reviews/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/reviews/index.html.erb
<%= @page_title = "レビュー一覧" %>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <ul>
        <%= render @reviews %>
      </ul>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/reviews/show.html.erb
<%= @page_title = "@room.nameの口コミ" %>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= @review.user.name %>
      <%= @review.content %>
      <%= link_to "add review", new_room_review_path(@room) %>
    </div>
  </div>
</div>